##########################
#
# CONFIG FILE FOR es_pancan_ga_all_TP.rds
#
##########################

input_file_paths:
  directory: "/media/deborah_oliveira/Data/LUND/9 THESIS/data/all_tcga/"
  rds: "es_pancan_ga_all_TP.rds"

gene_table_info:
  reporter_column_name: "ENSG"
  gene_symbol_column_name: "SYMBOL"
  
patient_annotation_info:
  sample_column_name: "sample_id"
  overall_survival_time_column_name: "OS.time"
  overall_survival_time_column_unit_table: "days"
  overall_survival_time_column_unit_desired: "years"
  overall_survival_event_column_name: "OS"
  
order_by:
  location_system_flip: ["SARC", "SKCM", "THCA", "PCPG", "ACC", "BLCA", "KIRP", 
                         "KIRC", "KICH", "PRAD", "TGCT", "CESC", "UCS", "UCEC",
                         "OV", "BRCA", "MESO", "THYM", "LUSC", "LUAD", "READ",
                         "COAD", "PAAD", "CHOL", "LIHC", "STAD", "ESCA", "HNSC", "LGG", "GBM", "UVM"]
  tru_percent_flip: ["SKCM", "TGCT", "CESC", "UCS", "UCEC", "READ", "COAD", "ESCA", 
                     "HNSC", "GBM", "OV", "BLCA", "SARC", "UVM", "LUSC", "STAD", "THYM", 
                     "CHOL", "MESO", "BRCA", "PAAD", "LIHC", "ACC", "LGG", "PCPG",
                     "KIRC", "KICH", "LUAD", "PRAD", "KIRP", "THCA"]

see_variables_by_clams:
  barplot:
  histogram:
  
survival_analysis:
  censor_at_timepoint: '5' 
  cancer_types_TRU: ["OV", "UVM", "CHOL", "BLCA", "SARC", "THYM", "MESO", "LUSC", 
                    "STAD", "ACC", "PAAD", "KICH", "PCPG", "LIHC", "BRCA", "LGG",
                    "KIRP", "KIRC", "LUAD", "PRAD", "THCA"]
  cancer_types_TRU_OS: ["THYM", "MESO", "LUSC", "STAD", "ACC", "PAAD", "KICH", 
                        "PCPG", "LIHC", "BRCA", "LGG", "KIRP", "KIRC", "LUAD", "PRAD", "THCA"] # >= 3 TRU

cox_regression:
  do_univariate:
  univariate_variables:
  do_multivariate:
  multivariate_variables:
  

survival_after_clams:
  variable_category1:
